### PR TITLE
Fix iss77

### LINKED ISSUE #77: В окне ‘Выйти без сохранения’ крестик не отменяет выход, а наоборот, выходит без сохранения.

### PR DESCRIPTION
**Pull request by IKhonakhbeeva**
Fixed #77 
Need to fix anouther bug: diagram closed without saving if tab was closed

### CODE REVIEW

File: qrgui/mainWindow/mainWindow.cpp [hunk 1]
```diff
@@ -606,10 +614,12 @@ void MainWindow::tryToSave()
 void MainWindow::closeAllTabs()
 {
 	const int tabCount = mUi->tabs->count();
-
+	QList<QWidget *> tabs = QList<QWidget *>();
```
Comment (iakov) [inline qrgui/mainWindow/mainWindow.cpp]: Можно просто `QList<QWidget *> tabs;`

File: qrgui/mainWindow/mainWindow.cpp [hunk 2]
```diff
@@ -606,10 +614,12 @@ void MainWindow::tryToSave()
...
 	for (int i = 0; i < tabCount; i++) {
-		closeTab(0);
+		tabs.append(mUi->tabs->widget(i));
 	}
+	for (QWidget * const tab : tabs)
```
Comment (iakov) [inline qrgui/mainWindow/mainWindow.cpp]: А `for (auto && tab : tabs) ...` чем-то хуже?
