### PR TITLE
Fix saving closed subprograms and some other situations

### LINKED ISSUE #805: Импорт / изменение подпрограмм не считается изменением проекта - закрывает без сожаления.
Импорт подпрограмм и их изменение не воспринимается как изменение в проекте.
Случайно нажал на крестик - закрылось ни о чём не спрашивая. Изменения - утеряны.

Думаю, можно мержить с изменениями в JS (не нашёл тикета, недавно был).

Т.е. изменения во вторичных окнах (подпрограммы, JS, ...) не воспринимаются как изменения в проекте.

### PR DESCRIPTION
**Pull request by IKhonakhbeeva**
Fixed #805

### CODE REVIEW

File: qrgui/mainWindow/projectManager/projectManagerWrapper.h [hunk 1]
```diff
@@ -75,6 +76,8 @@ public slots:
 	MainWindow *mMainWindow;
 	TextManagerInterface *mTextManager;
 	VersionsConverterManager mVersionsConverter;
+	bool mStackUnsaved;
```
Comment (iakov) [inline qrgui/mainWindow/projectManager/projectManagerWrapper.h:79]:
```suggestion
	bool mStackUnsaved { false };
```

File: qrgui/mainWindow/projectManager/projectManagerWrapper.cpp [hunk 2]
```diff
@@ -41,19 +41,23 @@ ProjectManagerWrapper::ProjectManagerWrapper(MainWindow *mainWindow, TextManager
 	, mMainWindow(mainWindow)
 	, mTextManager(textManager)
 	, mVersionsConverter(*mMainWindow)
+	, mStackUnsaved(false)
```
Comment (iakov) [inline qrgui/mainWindow/projectManager/projectManagerWrapper.cpp:44]:
```suggestion
```

File: qrgui/controller/controller.cpp [hunk 3]
```diff
@@ -120,6 +120,15 @@ void Controller::moduleClosed(const QString &moduleId)
 	resetAll();
 }
 
+bool Controller::isUnsaved(const QString &moduleId) const
+{
+	if (moduleId.isEmpty() || !mModuleStacks.keys().contains(moduleId))
+		return false;
+	if (mModuleStacks[moduleId] && !mModuleStacks[moduleId]->isClean())
+		return true;
+	return false;
```
Comment (iakov) [inline qrgui/controller/controller.cpp:129]:
```suggestion
	return !moduleId.isEmpty() && mModuleStacks.keys().contains(moduleId)
		&& mModuleStacks[moduleId] && !mModuleStacks[moduleId]->isClean();
```
