### PR TITLE
Fix #113. Improve/fix autocompletion

### LINKED ISSUE #113: Autocomplition in javascript was missed

### PR DESCRIPTION
**Pull request by iakov**
Fix #113

### CODE REVIEW

File: plugins/robots/interpreters/trikKitInterpreterCommon/src/trikTextualInterpreter.cpp [hunk 1]
```diff
@@ -73,6 +74,13 @@ trik::TrikTextualInterpreter::TrikTextualInterpreter(
 		qScriptRegisterMetaType<utils::AbstractTimer*>(engine, atimerToScriptValue, atimerFromScriptValue);
 	});
 	connect(&mScriptRunner, SIGNAL(completed(QString,int)), this, SLOT(scriptFinished(QString,int)));
+
+	using qReal::text::Languages;
+	using trikScriptRunner::ScriptType;
+	Languages::registerLanguage(Languages::javaScript(mScriptRunner.knownMethodNamesFor(ScriptType::JAVASCRIPT)));
+	Languages::registerLanguage(Languages::python(mScriptRunner.knownMethodNamesFor(ScriptType::PYTHON)));
+
```
Comment (anastasiia-kornilova) [inline plugins/robots/interpreters/trikKitInterpreterCommon/src/trikTextualInterpreter.cpp]: Unnecessary empty lines.

**Comment by anastasiia-kornilova** [comment]
I've checked, it works fine, but clean up code, please, before merge.
